"""initial schema

Revision ID: e28efea57d6e
Revises: 
Create Date: 2026-04-29 22:45:25.817193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28efea57d6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('reward_tokens_enabled', sa.Boolean(), nullable=False),
    sa.Column('reward_kes_enabled', sa.Boolean(), nullable=False),
    sa.Column('reward_sats_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('recycler', 'operator', 'company_admin', 'platform_admin', name='user_role_enum'), nullable=False),
    sa.Column('language', sa.Enum('en', 'sw', name='language_code_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payout_ledgers',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed_paid', 'disputed', name='payout_status_enum'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_ledgers_company_id'), 'payout_ledgers', ['company_id'], unique=False)
    op.create_index(op.f('ix_payout_ledgers_user_id'), 'payout_ledgers', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_table('sites',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_company_id'), 'sites', ['company_id'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('token_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lifetime_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lifetime_redeemed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_wallet_user_company')
    )
    op.create_index(op.f('ix_wallets_company_id'), 'wallets', ['company_id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('dropoffs',
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('recycler_id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('material_type', sa.Enum('plastic_bottle', 'glass_bottle', 'can', 'paper', 'ewaste', name='material_type_enum'), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('estimated_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('co2_avoided_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('reward_type', sa.Enum('tokens', 'kes', 'sats', name='reward_type_enum'), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reward_issued', sa.Boolean(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('record_hash', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recycler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dropoffs_company_id'), 'dropoffs', ['company_id'], unique=False)
    op.create_index(op.f('ix_dropoffs_confirmed_at'), 'dropoffs', ['confirmed_at'], unique=False)
    op.create_index(op.f('ix_dropoffs_material_type'), 'dropoffs', ['material_type'], unique=False)
    op.create_index(op.f('ix_dropoffs_operator_id'), 'dropoffs', ['operator_id'], unique=False)
    op.create_index(op.f('ix_dropoffs_recycler_id'), 'dropoffs', ['recycler_id'], unique=False)
    op.create_index(op.f('ix_dropoffs_site_id'), 'dropoffs', ['site_id'], unique=False)
    op.create_table('fraud_flags',
    sa.Column('dropoff_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'reviewed', 'dismissed', name='fraud_status_enum'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dropoff_id'], ['dropoffs.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_flags_dropoff_id'), 'fraud_flags', ['dropoff_id'], unique=False)
    op.create_index(op.f('ix_fraud_flags_reviewer_user_id'), 'fraud_flags', ['reviewer_user_id'], unique=False)
    op.create_table('reward_transactions',
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('dropoff_id', sa.String(length=36), nullable=True),
    sa.Column('reward_type', sa.Enum('tokens', 'kes', 'sats', name='reward_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dropoff_id'], ['dropoffs.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_transactions_dropoff_id'), 'reward_transactions', ['dropoff_id'], unique=False)
    op.create_index(op.f('ix_reward_transactions_wallet_id'), 'reward_transactions', ['wallet_id'], unique=False)
    op.create_table('sat_payouts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('dropoff_id', sa.String(length=36), nullable=True),
    sa.Column('sats_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='sat_payout_status_enum'), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['dropoff_id'], ['dropoffs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sat_payouts_company_id'), 'sat_payouts', ['company_id'], unique=False)
    op.create_index(op.f('ix_sat_payouts_dropoff_id'), 'sat_payouts', ['dropoff_id'], unique=False)
    op.create_index(op.f('ix_sat_payouts_user_id'), 'sat_payouts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sat_payouts_user_id'), table_name='sat_payouts')
    op.drop_index(op.f('ix_sat_payouts_dropoff_id'), table_name='sat_payouts')
    op.drop_index(op.f('ix_sat_payouts_company_id'), table_name='sat_payouts')
    op.drop_table('sat_payouts')
    op.drop_index(op.f('ix_reward_transactions_wallet_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_dropoff_id'), table_name='reward_transactions')
    op.drop_table('reward_transactions')
    op.drop_index(op.f('ix_fraud_flags_reviewer_user_id'), table_name='fraud_flags')
    op.drop_index(op.f('ix_fraud_flags_dropoff_id'), table_name='fraud_flags')
    op.drop_table('fraud_flags')
    op.drop_index(op.f('ix_dropoffs_site_id'), table_name='dropoffs')
    op.drop_index(op.f('ix_dropoffs_recycler_id'), table_name='dropoffs')
    op.drop_index(op.f('ix_dropoffs_operator_id'), table_name='dropoffs')
    op.drop_index(op.f('ix_dropoffs_material_type'), table_name='dropoffs')
    op.drop_index(op.f('ix_dropoffs_confirmed_at'), table_name='dropoffs')
    op.drop_index(op.f('ix_dropoffs_company_id'), table_name='dropoffs')
    op.drop_table('dropoffs')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_company_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_sites_company_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payout_ledgers_user_id'), table_name='payout_ledgers')
    op.drop_index(op.f('ix_payout_ledgers_company_id'), table_name='payout_ledgers')
    op.drop_table('payout_ledgers')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
